services:
  - type: web
    name: appccapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn crewcall.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crewcall.settings
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true 