# Generated by Django 5.2.3 on 2025-06-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='guest_pin',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='unique_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
