# Generated by Django 5.2.3 on 2025-06-19 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vessel_guest_pin_alter_vessel_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservessel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
