# Generated by Django 5.2.3 on 2025-06-20 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_guest_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guest'),
        ),
        migrations.AddField(
            model_name='task',
            name='predefined_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.predefinedmessage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
