# Generated by Django 5.2.3 on 2025-09-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='predefined_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.predefinedmessage'),
        ),
    ]
